// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CurrentPrice: typeof import('./components/CurrentPrice.vue')['default']
    FooterSection: typeof import('./components/footer-section.vue')['default']
    MainMenu: typeof import('./components/main-menu.vue')['default']
    MauritiusFuelPrices: typeof import('./components/mauritius-fuel-prices.vue')['default']
  }
}

export { }
